name: Add Nuitka assets to latest release

on:
  push:

permissions:
  contents: write

jobs:
  get_tag:
    runs-on: ubuntu-latest
    outputs:
      output: ${{ steps.latest_tag.outputs.tag }}

    steps:
      - uses: actions/checkout@v4
      - id: latest_tag
        run: |
          git fetch -a
          echo "tag=$(git tag --sort -committerdate | head -n 1)" >> $GITHUB_OUTPUT

  build:
    needs: get_tag

    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [macos-latest, windows-latest]

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - run: |
          python -m pip install --upgrade pip
          python -m pip install wheel
          python -m pip install -r requirements-core.txt -r requirements-gui.txt nuitka
          python -m pip install certifi
          python -m pip install zstandard ordered-set
          python -m pip install boto3 requests google-auth
          python -m pip install imageio

      - if: runner.os == 'macOS'
        run: |
            python -m nuitka --standalone --onefile --include-plugin-directory=. --include-package=timeago.locales.en_short --include-package=certifi --include-package=boto3 --include-package=requests --include-package=google --macos-create-app-bundle --macos-app-icon=icon.png --assume-yes-for-downloads --output-dir=dist emailproxy.py
            rm -rf dist/emailproxy.build dist/emailproxy.dist dist/emailproxy.onefile-build
      - if: runner.os == 'Windows'
        run: |
            python -m nuitka --standalone --onefile --include-plugin-directory=. --include-package=timeago.locales.en_short --include-package=certifi --include-package=boto3 --include-package=requests --include-package=google --windows-icon-from-ico=icon.png --assume-yes-for-downloads  --output-dir=dist emailproxy.py
            Remove-Item -Path "dist/emailproxy.build","dist/emailproxy.dist","dist/emailproxy.onefile-build" -Recurse -Force

      - run: |
          move LICENSE . 2> nul || { shopt -s expand_aliases; alias move=mv; }
          move LICENSE dist/
          move README.md dist/
          move emailproxy.config dist/
          echo 'This binary distribution is automatically created for each Email OAuth 2.0 Proxy release, ' >> _.txt
          echo 'but is not tested, and is not officially supported. Using the main emailproxy.py script ' >> _.txt
          echo 'directly is recommended for best results: https://github.com/simonrob/email-oauth2-proxy/' >> _.txt
          move _.txt dist/GettingStarted.txt

      - uses: thedoctor0/zip-release@0.7.6
        with:
          type: zip
          directory: dist/
          filename: emailproxy-${{ needs.get_tag.outputs.output }}_nuitka-${{ runner.os }}.zip

      - uses: xresloader/upload-to-github-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          file: dist/*.zip
          update_latest_release: true